[tool.poetry]
name = "msys2-web"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras = ["http2"], version = "^0.23.0"}
fastapi = "^0.87.0"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
aiofiles = "^22.1.0"
jinja2 = "^3.0.0"
fastapi-etag = "^0.4.0"
pgpdump = "^1.5"
gunicorn = "^20.0.4"
aiolimiter = "^1.0.0-beta.1"
pydantic = "^1.8.2"
zstandard = "^0.19.0"
MarkupSafe = "^2.1.1"

[tool.poetry.dev-dependencies]
mypy = "^0.991"
flake8 = "^5.0.0"
pytest = "^7.0.0"
requests = "^2.23.0"
respx = "^0.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
